theme: jekyll-theme-cayman
title: Desktube
description: Pops-out web video to your Desktop
github:
  zip_url: https://chrome.google.com/webstore/detail/desktube-chrome-extension/biejfabbjpibepifkhloolobibjjddia
  tar_url: https://github.com/johev09/desktube/releases/download/v1.0.0/desktube-setup-1.0.0.exe
show_downloads: true
